version: '3.11-slim'

services:
  fastapi-lessons:
    build:
      context: .
      dockerfile: Deployment.Dockerfile
    command: uvicorn "background_tasks:color_pallete_generator" --host 0.0.0.0 --port 3000
    ports:
      - "3000:3000"