# %% [md]
# # RAG ChatBot with FAISS Embedder and Local Vector Store
# ## Context
# Often it is necessary to augment the 'knowledge' of a ChatBot with
# information. This bridges the gap between the general knowledge 
# contained within General Pre-trained Transformer and specific 
# information which might not be available to GPT. One of the common 
# scenarios is that there is a temporal discrepancy between the time 
# when the GTP has been constituted, and the time when it is utilized. 
# The other is that the GPT does not posses domain specific knowledge to 
# provide responses with desired quality.
# ## Objective
# In this particular example, the objective is to augment the GPT with
# the information from the domain of *therapeutical massage*, 
# effectively transforming the transformer into an expert in the
# domain of sport and remedial massage.
# The book is utilized as the source of information which will be
# utilized for augmentation.
# ## Technological Stack
# The back-end of the whole system is the `LangChain`package, because
# of convenient interfaces to `TextLoader`, `PrompTemplate`, and 
# `ChatPromtTemplate`. In this particular implementation the choice
# has been made to make a *local* vector database via the `FAISS`
# package. Some further capabilities provided by `AIMessage`, and 
# `HumanMessage` classes are utilized as well, to fully benefit from
# `LangChain` package.
# Finally, embeddings are generated by OpenAIs `OpenAIEmbedding`, and
# the GPT has ben also selected within the OpenAIs eco-system. For the
# embedding model the choice has fallen to `text-embedding-ada-002`
# and `GPT-3.5-Turbo` has been selected as the ChatBot.
# ## Methodology
# The methodological approach for performing this task consists of
# following steps.
#   * Selection of the General Pre-trained Transformer that will serve
#   as the base generative model to perform question-answering task.
#   * Selection of the embedding model that will transform raw text
#   into its numerical representation
#   * Transformation of the additional information from the text-book
#   into its numerical information (embeddings). 
#   * Creation of the vector database to store the embeddings.
#   * Enrichment of the responses provided by the GPT by augmenting its
#   knowledge with additional information from the text-book which is
#   acquired according to its similarity to the question asked by
#   the user.
# # Implementation
# Let us start by import the necessary modules.
# %%
from utilities.general import environment_reader
from rag.embedding import GenericTextLoader, TextSplitter, \
    FAISSEmbedder, RAGChatBot
# %% [md]
# Let us declare the paths towards the input information from the book 
# about therapeutical massage.
# %% 
SOURCE_DOCUMENT = r'C:\Users\marko\Downloads\Sports And Remedial Massage Therapy ( PDFDrive ).pdf'
DOCUMENT_TYPE = 'pdf'
# %% [md]
# Let us read the PDF.
# %%
text_loader = GenericTextLoader(
    source_document=SOURCE_DOCUMENT,
    document_type=DOCUMENT_TYPE
)
text_loader.read_document()
document = text_loader.get_document()
# %% [md]
# Let us take a look how many pages there are in the document.
# %%
print(len(document))
# %% [md]
# Now it is necessary to split the documents into smaller sections, so
# that these sections can be transformed, into numerical 
# representations.
# %%
splitter = TextSplitter(document=document)
splitter.split_document()
converted_document = splitter.get_converted_document()
# %% [md]
# Let us take a look at the length of the document.
# %%
print(len(converted_document))
# %% [md]
# Let us now create a vector database locally via FEISS library.
# %%
local_index = FAISSEmbedder(
    pieces_of_text=converted_document,
    local_database='massage_bot',
    database_name='massage_bot'
)
local_index.create_vector_database()
# %% [md]
# As mentioned earlier, the database will be stored locally.
# %%
local_index.save_vector_database()
vector_database = local_index.get_vector_store()
# %% [md]
# Let us try the chat-bot.
# %%
chat_bot = RAGChatBot(vector_database=vector_database)
chat_bot.start_chat()